/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import controller.NewController;
import deepspace.SpaceFighter;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author germanpadua
 */
public class ArraySpaceFightersView extends javax.swing.JPanel {

    /**
     * Creates new form ArraySpaceFightersView
     */
    public ArraySpaceFightersView() {
        initComponents();
    }
    public ArrayList <Integer> getSelectedInHangar(){
        ArrayList <Integer> selected = new ArrayList<>();
        
        for(int i=0; i<stations_panel.getComponentCount(); i++){
            Component c = stations_panel.getComponent(i);
            if(((SpaceFighterView) c).isSelected()){
                selected.add(i);
            }
        }
         return selected;   
    }
    
    public void setArraySpaceFightersView(ArrayList<SpaceFighter> sp){
        stations_panel.removeAll();
        
        for(int i=0; i<sp.size(); i++){
                SpaceFighterView spv = new SpaceFighterView();
                spv.setSpaceFighterView(sp.get(i));
                stations_panel.add(spv);
        }
        
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stations_scroll = new javax.swing.JScrollPane();
        stations_panel = new javax.swing.JPanel();

        stations_scroll.setViewportView(stations_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stations_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stations_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel stations_panel;
    private javax.swing.JScrollPane stations_scroll;
    // End of variables declaration//GEN-END:variables
}
